spring:
  cloud:
    gateway:
      #表示注册中心生效，我们可以通过注册中心的服务名进行路由转发
      locator:
        enabled: true
      routes:
        # 认证中心，表示路由的唯一id
        - id: insightCloud-auth
          #指向注册中心的服务
          uri: lb://insightCloud-auth
          #表示要进行的断言
          predicates:
            #表示path地址，根据url，以auth开头的会被转发到auth-service服务，需要注意的是后面/**和/*的区别
            - Path=/auth/**
          #过滤器
          filters:
          #截取url，本例中就是会把/auth截掉，后面的部分才是转发的url
          - StripPrefix=1
#            # 验证码处理
#            - ValidateCodeGatewayFilter
#            # 前端密码解密
#            - PasswordDecoderFilter
        #insightCloud-system 模块
        #表示路由的唯一id
        - id: insightCloud-system
          uri: lb://insightCloud-system
          predicates:
            - Path=/system/**
          filters:
          - StripPrefix=1
#            # 限流配置
#            - name: RequestRateLimiter
#              args:
#                key-resolver: '#{@remoteAddrKeyResolver}'
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#              # 降级配置
#            - name: Hystrix
#              args:
#                name: default
#                fallbackUri: 'forward:/fallback'


#security:
#  encode:
#    # 前端密码密钥，必须16位
#    key: 'thanks,pig4cloud'
#
## 不校验验证码终端
#ignore:
#  clients:
#    - test