# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      #主键类型 0:数据库ID自增, 1:用户输入ID,2:全局唯一ID (数字类型唯一ID), 3:全局唯一ID UUID
      id-type: 0
      #字段策略(拼接sql时用于判断属性值是否拼接) 0:忽略判断,1:非NULL判断,2:非空判断
      field-strategy: 1
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 暴露监控端点
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    bus-refresh:
      enabled: true
    refresh:
      enabled: true

spring:
  cloud:
    bus:
      refresh:
        enabled: true #动态刷新配置
      trace:
        enabled: true #开启消息跟踪
  #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

insight: 1323